### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by atremblay** [atremblay/chronoRNN#3]
This is not exhaustive

- [ ] Implement the code for the experiments
   - [x] Models:
      - [x] VanillaRNNs
      - [x] LeakyRNNs
      - [x] GatedRNNs
      - [x] VanillaLSTM
      - [x] ChronoLSTM
   - [ ] Tasks:
      - [x]  Add
      - [ ] Warp
      - [ ] Copy
- [ ] Do the experiments
   - [ ]  Add
      - [ ] LeakyRNNs
      - [ ] GatedRNNs
      - [ ] VanillaLSTM
      - [ ] ChronoLSTM
   - [ ] Warp
      - [ ] LeakyRNNs
      - [ ] GatedRNNs
      - [ ] VanillaLSTM
      - [ ] ChronoLSTM
   - [ ] Copy
      - [ ] LeakyRNNs
      - [ ] GatedRNNs
      - [ ] VanillaLSTM
      - [ ] ChronoLSTM
- [ ] Complete the report
